CLASS ybp_i_invoice_attach DEFINITION
  PUBLIC
  ABSTRACT
  FINAL FOR BEHAVIOR OF YI_Invoice_Attach.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ybp_i_invoice_attach IMPLEMENTATION.
ENDCLASS.
